name: Common CI CD

on:
  workflow_call:
    inputs:
      app-type:
        required: true
        type: string
      micro-services:
        required: true
        type: string


jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run to build file
        if: ${{ inputs.app-type  == 'java' }}
        run: mvn clean package
      - name: Upload Artifact
        if: ${{ inputs.app-type  == 'java' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.micro-services }}-jar
          path: target/${{ inputs.micro-services }}-1.0.jar
          retention-days: 1

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a One line test
        if: ${{ inputs.app-type  == 'nodejs' }}
        run: echo npm test
      - name: Run a One line test
        if: ${{ inputs.app-type  == 'java' }}
        run: echo mvn test
      - name: Run a One line test
        if: ${{ inputs.app-type  == 'python' }}
        run: echo pytest test.py

  docker:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login for pushing image
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 444206648334.dkr.ecr.us-east-1.amazonaws.com
      - name: Download Artifact
        if: ${{ inputs.app-type  == 'java' }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.micro-services }}-jar
          path: ./
      - name: Docker Build
        run: docker build -t 444206648334.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.micro-services }} .
      - name: Docker Push
        run: docker push 444206648334.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.micro-services }}

  dev-deploy:
    needs: docker
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ckolli66/roboshop-helm-v1
      - name: Get kubectl config
        run: aws eks update-kubeconfig --name dev
      - name: Helm deploy app
        run: helm upgrade -i ${{ inputs.micro-services }} . -f microservice-specific-valuesFiles/${{ inputs.micro-services }}.yml
      - name: ArgoCd Login
        run: |
          url=$(kubectl get svc argocd-server -o jsonpath='{.status.loadBalancer.ingress[*].hostname}')
          password=$(kubectl get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode)
          argocd login $url --username admin --password $password --insecure
      - name: Create App in ArgoCd
        run: argocd app create ${{ inputs.micro-services }} --repo https://github.com/ckolli66/roboshop-helm-v1.git --path . --dest-namespace default --dest-server https://kubernetes.default.svc --values microservice-specific-valuesFiles/${{ inputs.micro-services }}.yml
      - name: Sync App
        run: argocd app sync ${{ inputs.micro-services }}
      - name: ArgoCd App Health Check
        run: argocd app wait ${{ inputs.micro-services }}

  qa-deploy:
    needs: dev-deploy
    runs-on: self-hosted
    environment: qa
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ckolli66/roboshop-helm-v1
      - name: Get kubectl config
        run: aws eks update-kubeconfig --name dev
      - name: Helm deploy app
        run: echo helm upgrade -i ${{ inputs.micro-services }} . -f microservice-specific-valuesFiles/${{ inputs.micro-services }}.yml

  uat-deploy:
    needs: qa-deploy
    runs-on: self-hosted
    environment: uat
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ckolli66/roboshop-helm-v1
      - name: Get kubectl config
        run: aws eks update-kubeconfig --name dev
      - name: Helm deploy app
        run: echo helm upgrade -i ${{ inputs.micro-services }} . -f microservice-specific-valuesFiles/${{ inputs.micro-services }}.yml

  prod-deploy:
    needs: uat-deploy
    runs-on: self-hosted
    environment: prod
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ckolli66/roboshop-helm-v1
      - name: Get kubectl config
        run: aws eks update-kubeconfig --name dev
      - name: Helm deploy app
        run: echo helm upgrade -i ${{ inputs.micro-services }} . -f microservice-specific-valuesFiles/${{ inputs.micro-services }}.yml

